name: Deploy to development environment (GH page)

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js 16.17.0 (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the application
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          